module.exports.INVALID_QUERY_PARAMETER = 'Invalid query parameter.'
module.exports.ACCESS_DENIED= 'Access denied. Please check logged in first.'
module.exports.SESSION_NOT_FOUND = 'Already Logged out.'
module.exports.INVALID_POST_REQUEST = 'Invaild post request. Please check data it exists or has proper type '
module.exports.UNEXPECTED_FIELD_ERROR = 'Unexpedted field error. Please check post reqeust it has proper name'
module.exports.CONFLICT_PARAMETER = 'Conflict parameter.'
module.exports.FACEBOOK_LOGIN_FAIL = 'Facebook login failed. Make sure accepted requests'
module.exports.INCORRECT_USERNAME = 'Incorrect username.',
module.exports.INCORRECT_PASSWORD = 'Incorrect password.' 